# Generated by Django 4.2.7 on 2024-02-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id_anime', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_anime', models.CharField(max_length=45)),
                ('image', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'anime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_favorito', models.AutoField(primary_key=True, serialize=False)),
                ('es_favorito', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'favorito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id_personaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_personaje', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'personaje',
                'managed': False,
            },
        ),
    ]
